# Generated by Django 5.0.4 on 2024-05-30 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='parent_event_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='registration_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
